(function(){
const PUBLIC_URL='https://utty1985-beep.github.io/Unamano/';
let chatPeer=null,chatJob=null,msgs=[],profiles=new Map(),chatChannel=null;
const q=id=>document.getElementById(id);
const safe=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

window.addEventListener('load',()=>setTimeout(initExtra,0));

function initExtra(){
 if(typeof sb==='undefined'||!sb)return;
 addStyles(); addProfileInputs(); addMessagesSection(); patchGo(); patchAuth(); patchProfile(); patchJob(); patchActivity(); patchLoginLogout();
 if(typeof session!=='undefined'&&session)startMessaging();
}

function addStyles(){
 if(q('umExtraStyle'))return; const s=document.createElement('style'); s.id='umExtraStyle'; s.textContent=`
 .avatar.photo{overflow:hidden;padding:0;background:#fff}.avatar.photo img{width:100%;height:100%;object-fit:cover;display:block}.upload-note{font-size:12px;color:var(--muted);margin-top:5px}.cvbox{margin-top:12px;padding:12px;border:1px solid var(--line);border-radius:14px;background:#f8fbfa}.msggrid{display:grid;grid-template-columns:minmax(230px,.6fr) minmax(0,1.4fr);gap:16px}.threads{max-height:65vh;overflow:auto}.thread{border:1px solid var(--line);border-radius:13px;padding:10px;margin:8px 0;cursor:pointer}.thread.active,.thread:hover{background:#f6fbf9;border-color:#9acdbb}.threadprev{font-size:12px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat{min-height:430px;display:flex;flex-direction:column}.chathead{display:flex;gap:9px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:10px}.chatscroll{flex:1;max-height:52vh;overflow:auto;padding:12px 0;display:flex;flex-direction:column;gap:8px}.bubble{max-width:78%;padding:9px 11px;border-radius:15px;background:#e7eef6;color:#263c51;align-self:flex-start;word-break:break-word}.bubble.me{background:var(--g);color:#fff;align-self:flex-end}.bubble .sender{display:block;font-size:13px;font-weight:700;margin-bottom:3px}.bubble time{font-size:10px;opacity:.7;display:block;margin-top:3px}.compose{display:grid;grid-template-columns:1fr auto;gap:8px;border-top:1px solid var(--line);padding-top:10px}.compose textarea{min-height:48px;margin:0}.back-to-threads{display:none}@media(max-width:840px){.msggrid{grid-template-columns:1fr}.threads{max-height:30vh}.msggrid.chat-open>div:first-child{display:none}.msggrid:not(.chat-open)>#chatPanel{display:none}.back-to-threads{display:inline-flex}.bottom{grid-template-columns:repeat(6,1fr)!important}}`;
 document.head.appendChild(s);
}

function addProfileInputs(){
 const card=document.querySelector('#profile aside .card'); if(!card||q('profilePhoto'))return;
 const save=[...card.querySelectorAll('button')].find(b=>/Salva profilo/i.test(b.textContent||'')); if(!save)return;
 const box=document.createElement('div'); box.innerHTML=`<label for="profilePhoto">Foto profilo</label><input id="profilePhoto" type="file" accept="image/jpeg,image/png,image/webp"><div class="upload-note">JPG, PNG o WEBP · massimo 5 MB</div><label for="pcv">Curriculum / esperienza</label><textarea id="pcv" maxlength="3000" placeholder="Esperienze, formazione, capacità e disponibilità"></textarea><label for="profileCv">Curriculum da allegare</label><input id="profileCv" type="file" accept="application/pdf,.pdf,.doc,.docx"><div class="upload-note">PDF, DOC o DOCX · massimo 10 MB</div><div id="cvCurrent" class="upload-note"></div>`;
 while(box.firstChild)save.parentNode.insertBefore(box.firstChild,save);
}

function addMessagesSection(){
 if(!q('messages')){const sec=document.createElement('section');sec.id='messages';sec.className='hidden';sec.innerHTML=`<div class="section-head"><div><h2>Messaggi privati</h2><div class="small">Parla direttamente con gli altri utenti senza pubblicare telefono o email.</div></div><button class="btn g sm" onclick="loadPrivateMessages()">Aggiorna</button></div><div class="msggrid"><div class="card"><h3 style="margin-top:0">Conversazioni</h3><div id="chatThreads" class="threads"></div></div><div id="chatPanel" class="card chat"><div class="empty"><span class="emoji">💬</span><b>Seleziona una conversazione</b></div></div></div>`;q('legal')?.parentNode.insertBefore(sec,q('legal'));}
 if(!q('msgTop')){const b=document.createElement('button');b.id='msgTop';b.className='navbtn';b.innerHTML='Messaggi <span id="msgBadge" class="badge hidden">0</span>';b.onclick=()=>need(()=>go('messages'));q('authTop')?.before(b);}
 if(!q('msgMobile')){const b=document.createElement('button');b.id='msgMobile';b.dataset.nav='messages';b.innerHTML='<i>💬</i>Chat<span id="msgBadgeMob" class="badge hidden">0</span>';b.onclick=()=>need(()=>go('messages'));document.querySelector('.bottom button[data-nav="profile"]')?.before(b);}
}

function patchGo(){
 if(window.__umGo)return;window.__umGo=1;const old=window.go;window.go=function(id){q('messages')?.classList.add('hidden');if(id!=='messages')return old(id);if(!session)return old('auth');try{currentSection='messages'}catch(e){};['home','auth','new','activity','profile','legal'].forEach(x=>q(x)?.classList.add('hidden'));q('messages')?.classList.remove('hidden');document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.nav==='messages'));scrollTo({top:0,behavior:'instant'});loadPrivateMessages();};
}

function patchAuth(){
 window.signup=async function(){if(!sb)return;const n=q('name')?.value.trim()||'',e=q('email')?.value.trim()||'',p=q('pass')?.value||'';if(n.length<2||!e||p.length<8){q('msg').textContent='Compila nome, email e password di almeno 8 caratteri.';return}q('authSubmit').disabled=true;const r=await sb.auth.signUp({email:e,password:p,options:{data:{display_name:n},emailRedirectTo:PUBLIC_URL}});q('authSubmit').disabled=false;if(r.error){q('msg').textContent=r.error.message;return}if(r.data.session){try{session=r.data.session}catch(e){};updateAuth();toast('Account creato. Benvenuto su UnaMano!');await loadAll();go('home')}else q('msg').textContent='Registrazione effettuata. Controlla la tua email e conferma l’account: il link tornerà su UnaMano.';};
 window.resetPw=async function(){const e=q('email')?.value.trim()||'';if(!e)return q('msg').textContent='Inserisci prima la tua email.';const r=await sb.auth.resetPasswordForEmail(e,{redirectTo:PUBLIC_URL});q('msg').textContent=r.error?r.error.message:'Email di recupero inviata. Controlla la posta.';};
 window.resendConfirmation=async function(){const e=q('email')?.value.trim()||'';if(!e)return q('msg').textContent='Inserisci prima la tua email.';const r=await sb.auth.resend({type:'signup',email:e,options:{emailRedirectTo:PUBLIC_URL}});q('msg').textContent=r.error?r.error.message:'Nuova email di conferma inviata.';};
 const forgot=q('forgotBtn');if(forgot&&!q('resendConfirm')){const b=document.createElement('button');b.id='resendConfirm';b.className='btn g';b.style.cssText='width:100%;margin-top:8px';b.textContent='Reinvia email di conferma';b.onclick=resendConfirmation;forgot.insertAdjacentElement('afterend',b);}
}

function ext(f){return((f?.name||'').split('.').pop()||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function avatarPath(url){const m='/storage/v1/object/public/avatars/';const i=String(url||'').indexOf(m);return i<0?null:decodeURIComponent(String(url).slice(i+m.length))}

function patchProfile(){
 const oldLoad=window.loadProfile;window.loadProfile=async function(){await oldLoad.apply(this,arguments);await enhanceOwnProfile();};
 window.saveProfile=async function(){
  if(!session)return;const uid=session.user.id,name=q('pn')?.value.trim()||'',city=q('pc')?.value.trim()||'',bio=q('pb')?.value.trim()||'',skills=(q('ps')?.value||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,12),cv_summary=q('pcv')?.value.trim()||'';if(name.length<2)return toast('Inserisci un nome pubblico.','warn');
  const cur=await sb.from('profiles').select('avatar_url,cv_path,cv_filename').eq('id',uid).single();if(cur.error)return toast(errText(cur.error),'err');let avatar_url=cur.data.avatar_url||null,cv_path=cur.data.cv_path||null,cv_filename=cur.data.cv_filename||null;
  const photo=q('profilePhoto')?.files?.[0];if(photo){if(photo.size>5*1024*1024)return toast('La foto supera 5 MB.','warn');if(!['image/jpeg','image/png','image/webp'].includes(photo.type))return toast('Usa JPG, PNG o WEBP.','warn');const path=`${uid}/avatar-${Date.now()}.${ext(photo)||'jpg'}`;const up=await sb.storage.from('avatars').upload(path,photo,{contentType:photo.type});if(up.error)return toast('Errore foto: '+errText(up.error),'err');avatar_url=sb.storage.from('avatars').getPublicUrl(path).data.publicUrl;const old=avatarPath(cur.data.avatar_url);if(old)sb.storage.from('avatars').remove([old]);}
  const cv=q('profileCv')?.files?.[0];if(cv){if(cv.size>10*1024*1024)return toast('Il curriculum supera 10 MB.','warn');const ex=ext(cv);if(!['pdf','doc','docx'].includes(ex))return toast('Usa PDF, DOC o DOCX.','warn');const path=`${uid}/cv-${Date.now()}.${ex}`;const up=await sb.storage.from('curricula').upload(path,cv,{contentType:cv.type||undefined});if(up.error)return toast('Errore curriculum: '+errText(up.error),'err');if(cv_path)sb.storage.from('curricula').remove([cv_path]);cv_path=path;cv_filename=cv.name;}
  const r=await sb.from('profiles').update({display_name:name,city:city||null,bio:bio||null,skills,avatar_url,cv_summary:cv_summary||null,cv_path,cv_filename,updated_at:new Date().toISOString()}).eq('id',uid);if(r.error)return toast(errText(r.error),'err');q('profilePhoto').value='';q('profileCv').value='';toast('Profilo salvato online.');await loadJobs();await loadProfile();
 };
 window.removeCurriculum=async function(){if(!session)return;const r=await sb.from('profiles').select('cv_path').eq('id',session.user.id).single();if(r.data?.cv_path)await sb.storage.from('curricula').remove([r.data.cv_path]);await sb.from('profiles').update({cv_path:null,cv_filename:null}).eq('id',session.user.id);toast('Curriculum rimosso.');loadProfile();};
}

async function enhanceOwnProfile(){
 addProfileInputs();if(!session)return;const r=await sb.from('profiles').select('display_name,city,bio,skills,avatar_url,cv_summary,cv_path,cv_filename').eq('id',session.user.id).single();if(r.error)return;const p=r.data;if(q('pcv'))q('pcv').value=p.cv_summary||'';const av=document.querySelector('#profileBox .avatar.lg');if(av&&p.avatar_url){av.classList.add('photo');av.innerHTML=`<img src="${safe(p.avatar_url)}" alt="Foto profilo">`;}const card=document.querySelector('#profileBox .card');card?.querySelector('#ownCvBox')?.remove();if(card&&(p.cv_summary||p.cv_path)){const d=document.createElement('div');d.id='ownCvBox';d.className='cvbox';d.innerHTML=`<b>Curriculum</b>${p.cv_summary?`<p>${safe(p.cv_summary)}</p>`:''}${p.cv_path?`<div class="small">📎 ${safe(p.cv_filename||'Curriculum allegato')}</div>`:''}`;card.appendChild(d);}if(q('cvCurrent'))q('cvCurrent').innerHTML=p.cv_path?`Attuale: <b>${safe(p.cv_filename||'Curriculum')}</b> <button class="btn d sm" type="button" onclick="removeCurriculum()">Rimuovi</button>`:'Nessun curriculum allegato.';
}

window.openUserProfile=async function(uid){
 const [pr,rr,jr]=await Promise.all([sb.from('profiles').select('id,display_name,city,bio,skills,avatar_url,cv_summary,cv_path,cv_filename').eq('id',uid).single(),sb.from('reviews').select('stars').eq('subject_id',uid),sb.from('jobs').select('id,status').eq('owner_id',uid)]);if(pr.error)return toast(errText(pr.error),'err');const p=pr.data,rev=rr.data||[],mine=jr.data||[],avg=rev.length?(rev.reduce((a,x)=>a+x.stars,0)/rev.length).toFixed(1):'—';let cvUrl=null;if(session&&p.cv_path){const s=await sb.storage.from('curricula').createSignedUrl(p.cv_path,600);if(!s.error)cvUrl=s.data.signedUrl;}const me=session?.user?.id===uid;showModal(`<div class="modal-head"><h2 style="margin:0">Profilo utente</h2><button class="iconbtn" onclick="closeModal()">✕</button></div><div class="profile-head" style="margin-top:12px"><div class="avatar lg ${p.avatar_url?'photo':''}">${p.avatar_url?`<img src="${safe(p.avatar_url)}" alt="Foto profilo">`:safe((p.display_name?.[0]||'U').toUpperCase())}</div><div><h2>${safe(p.display_name||'Utente')}</h2><div class="small">📍 ${safe(p.city||'Città non indicata')}</div></div></div><p>${safe(p.bio||'Nessuna presentazione.')}</p><div class="skills">${(p.skills||[]).map(x=>`<span class="chip">${safe(x)}</span>`).join('')}</div><div class="metric-grid"><div class="metric"><b>${avg}</b><span>valutazione</span></div><div class="metric"><b>${rev.length}</b><span>recensioni</span></div><div class="metric"><b>${mine.filter(x=>x.status==='open').length}</b><span>annunci aperti</span></div></div>${(p.cv_summary||p.cv_path)?`<div class="cvbox"><b>Curriculum</b>${p.cv_summary?`<p>${safe(p.cv_summary)}</p>`:''}${p.cv_path?(cvUrl?`<a class="btn g sm" href="${safe(cvUrl)}" target="_blank" rel="noopener">Apri ${safe(p.cv_filename||'curriculum')}</a>`:'<div class="small">Accedi per aprire il curriculum allegato.</div>'):''}</div>`:''}<div class="actions">${!me?`<button class="btn p" onclick="closeModal();openConversation('${uid}')">💬 Messaggio privato</button>`:''}<button class="btn g" onclick="closeModal()">Chiudi</button></div>`);
};

function patchJob(){if(window.__umJob)return;window.__umJob=1;const old=window.openJob;window.openJob=function(id){old.apply(this,arguments);const j=jobs.find(x=>x.id===id);if(!j)return;setTimeout(()=>{const a=document.querySelector('#modalRoot .modal .actions');if(!a||a.dataset.extra)return;a.dataset.extra='1';const p=document.createElement('button');p.className='btn g';p.textContent='👤 Profilo';p.onclick=()=>openUserProfile(j.owner_id);a.appendChild(p);if(session?.user?.id!==j.owner_id){const m=document.createElement('button');m.className='btn g';m.textContent='💬 Messaggio';m.onclick=()=>{closeModal();openConversation(j.owner_id,j.id)};a.appendChild(m)}},0)};}

function patchActivity(){if(window.__umAct)return;window.__umAct=1;const old=window.renderActivity;window.renderActivity=function(){const r=old.apply(this,arguments);setTimeout(addActivityButtons,0);return r};}
function addActivityButtons(){if(!session)return;const map=new Map(jobs.map(j=>[j.id,j])),uid=session.user.id,inc=applications.filter(a=>map.get(a.job_id)?.owner_id===uid),out=applications.filter(a=>a.applicant_id===uid);document.querySelectorAll('#incomingApps .appcard').forEach((c,i)=>{const a=inc[i];if(!a||c.dataset.extra)return;c.dataset.extra='1';const x=document.createElement('div');x.className='actions';x.innerHTML=`<button class="btn g sm" onclick="openUserProfile('${a.applicant_id}')">👤 Profilo</button><button class="btn g sm" onclick="openConversation('${a.applicant_id}','${a.job_id}')">💬 Messaggio</button>`;c.appendChild(x)});document.querySelectorAll('#outgoingApps .appcard').forEach((c,i)=>{const a=out[i],j=a&&map.get(a.job_id);if(!j||c.dataset.extra)return;c.dataset.extra='1';const x=document.createElement('div');x.className='actions';x.innerHTML=`<button class="btn g sm" onclick="openUserProfile('${j.owner_id}')">👤 Profilo</button><button class="btn g sm" onclick="openConversation('${j.owner_id}','${a.job_id}')">💬 Messaggio</button>`;c.appendChild(x)});}

function patchLoginLogout(){if(window.__umSession)return;window.__umSession=1;const ol=window.login;window.login=async function(){const r=await ol.apply(this,arguments);if(session)startMessaging();return r};const oo=window.logout;window.logout=async function(){if(chatChannel)try{await sb.removeChannel(chatChannel)}catch(e){};chatChannel=null;msgs=[];profiles.clear();setBadges(0);return oo.apply(this,arguments)};}
async function startMessaging(){if(!session)return;await unread();if(chatChannel)try{await sb.removeChannel(chatChannel)}catch(e){};chatChannel=sb.channel('um-msg-'+session.user.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`recipient_id=eq.${session.user.id}`},()=>{toast('Nuovo messaggio privato.');loadPrivateMessages()}).subscribe();}
async function unread(){if(!session)return;const r=await sb.from('messages').select('id',{count:'exact',head:true}).eq('recipient_id',session.user.id).is('read_at',null);if(!r.error)setBadges(r.count||0)}
function setBadges(n){['msgBadge','msgBadgeMob'].forEach(id=>{const e=q(id);if(e){e.textContent=n;e.classList.toggle('hidden',!n)}})}

window.loadPrivateMessages=async function(){if(!session)return;const uid=session.user.id,r=await sb.from('messages').select('id,sender_id,recipient_id,job_id,body,created_at,read_at').or(`sender_id.eq.${uid},recipient_id.eq.${uid}`).order('created_at',{ascending:true}).limit(1000);if(r.error){q('chatThreads').innerHTML=`<div class="notice dangerbox">${safe(errText(r.error))}</div>`;return}msgs=r.data||[];const ids=[...new Set(msgs.map(m=>m.sender_id===uid?m.recipient_id:m.sender_id))];profiles=new Map();if(ids.length){const p=await sb.from('profiles').select('id,display_name,city,avatar_url').in('id',ids);(p.data||[]).forEach(x=>profiles.set(x.id,x))}renderThreads();setBadges(msgs.filter(m=>m.recipient_id===uid&&!m.read_at).length);if(chatPeer)renderConversation(chatPeer);};
function renderThreads(){const box=q('chatThreads'),uid=session.user.id,map=new Map();msgs.forEach(m=>{const p=m.sender_id===uid?m.recipient_id:m.sender_id;if(!map.has(p))map.set(p,[]);map.get(p).push(m)});const arr=[...map.entries()].map(([p,a])=>({p,a,last:a[a.length-1],un:a.filter(m=>m.recipient_id===uid&&!m.read_at).length})).sort((a,b)=>new Date(b.last.created_at)-new Date(a.last.created_at));box.innerHTML=arr.length?arr.map(x=>{const p=profiles.get(x.p)||{};return`<div class="thread ${chatPeer===x.p?'active':''}" onclick="openConversation('${x.p}','${x.last.job_id||''}')"><div><b>${safe(p.display_name||'Utente')}</b>${x.un?` <span class="badge">${x.un}</span>`:''}</div></div>`}).join(''):'<div class="empty">Nessuna conversazione.</div>';}
window.openConversation=async function(peer,job){if(!session)return need(()=>{});if(peer===session.user.id)return;chatPeer=peer;chatJob=job||null;q('messages')?.querySelector('.msggrid')?.classList.add('chat-open');go('messages');await loadPrivateMessages();await renderConversation(peer);};
async function renderConversation(peer){if(!session)return;const p=profiles.get(peer)||(await sb.from('profiles').select('id,display_name,city,avatar_url').eq('id',peer).single()).data||{};profiles.set(peer,p);const uid=session.user.id,list=msgs.filter(m=>(m.sender_id===uid&&m.recipient_id===peer)||(m.sender_id===peer&&m.recipient_id===uid));const unreadIds=list.filter(m=>m.recipient_id===uid&&!m.read_at).map(m=>m.id);if(unreadIds.length){await sb.from('messages').update({read_at:new Date().toISOString()}).in('id',unreadIds);list.forEach(m=>{if(unreadIds.includes(m.id))m.read_at=new Date().toISOString()});unread()};q('messages')?.querySelector('.msggrid')?.classList.add('chat-open');q('chatPanel').innerHTML=`<div class="chathead"><button class="btn g sm back-to-threads" onclick="showChatThreads()" aria-label="Torna alle conversazioni">←</button><div class="avatar ${p.avatar_url?'photo':''}">${p.avatar_url?`<img src="${safe(p.avatar_url)}" alt="">`:safe((p.display_name?.[0]||'U').toUpperCase())}</div><div><b>${safe(p.display_name||'Utente')}</b><div class="small">${safe(p.city||'')}</div></div><div class="sp"></div><button class="btn g sm" onclick="openUserProfile('${peer}')">Profilo</button></div><div id="chatScroll" class="chatscroll">${list.length?list.map(m=>`<div class="bubble ${m.sender_id===uid?'me':''}">${m.sender_id===uid?'':`<span class="sender">${safe(p.display_name||'Utente')}:</span>`}${safe(m.body)}<time>${new Date(m.created_at).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty">Inizia la conversazione.</div>'}</div><div class="compose"><textarea id="chatText" maxlength="2000" placeholder="Scrivi un messaggio privato"></textarea><button class="btn p" onclick="sendPrivateMessage()">Invia</button></div>`;setTimeout(()=>{const x=q('chatScroll');if(x)x.scrollTop=x.scrollHeight},0);renderThreads();}
window.showChatThreads=function(){q('messages')?.querySelector('.msggrid')?.classList.remove('chat-open')};
window.sendPrivateMessage=async function(){if(!session||!chatPeer)return;const t=q('chatText')?.value.trim()||'';if(!t)return;const r=await sb.from('messages').insert({sender_id:session.user.id,recipient_id:chatPeer,job_id:chatJob||null,body:t});if(r.error)return toast(errText(r.error),'err');q('chatText').value='';await loadPrivateMessages();await renderConversation(chatPeer);};
})();
