// Pure alert rules, independent of map, sensors and network.
function createPfcAlertEngine(emit){
 const near=new Map(),areas=new Map();let territory=null;const weatherSeen=new Map();
 const valid=p=>p&&p.lat!==null&&p.lng!==null&&Number.isFinite(+p.lat)&&Number.isFinite(+p.lng)&&Math.abs(+p.lat)<=90&&Math.abs(+p.lng)<=180;
 const distance=(a,b)=>{const r=Math.PI/180,x=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lng-a.lng)*r/2)**2;return 6371000*2*Math.asin(Math.min(1,Math.sqrt(x)))};
 const same=(a,b)=>Math.abs(a[0]-b[0])<1e-7&&Math.abs(a[1]-b[1])<1e-7;
 function rings(segments){const pending=segments.map(s=>s.slice()).filter(s=>s.length>=2),out=[];while(pending.length){let ring=pending.shift(),changed=true;while(!same(ring[0],ring.at(-1))&&changed){changed=false;for(let i=0;i<pending.length;i++){let s=pending[i];if(same(ring.at(-1),s[0]))ring.push(...s.slice(1));else if(same(ring.at(-1),s.at(-1)))ring.push(...s.slice().reverse().slice(1));else if(same(ring[0],s.at(-1)))ring=s.slice(0,-1).concat(ring);else if(same(ring[0],s[0]))ring=s.slice().reverse().slice(0,-1).concat(ring);else continue;pending.splice(i,1);changed=true;break}}if(ring.length>=4&&same(ring[0],ring.at(-1)))out.push(ring)}return out}
 function parseAreas(elements){const out=[],seen=new Set();for(const e of elements||[]){const id=e.type+':'+e.id;if(seen.has(id))continue;seen.add(id);const geom=g=>(g||[]).filter(p=>valid({lat:p.lat,lng:p.lon})).map(p=>[+p.lon,+p.lat]);let outer=[],inner=[];if(e.type==='way')outer=rings([geom(e.geometry)]);else if(e.type==='relation'){outer=rings((e.members||[]).filter(m=>m.type==='way'&&(!m.role||m.role==='outer')).map(m=>geom(m.geometry)));inner=rings((e.members||[]).filter(m=>m.role==='inner').map(m=>geom(m.geometry)))}if(outer.length)out.push({id,name:e.tags?.name||'Area protetta',outer,inner})}return out}
 function inRing(p,ring){let inside=false;const x=+p.lng,y=+p.lat;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
 function boundaryDistance(p,rings){let best=Infinity;const kx=111320*Math.cos(p.lat*Math.PI/180),ky=111320;for(const ring of rings)for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i],ax=(a[0]-p.lng)*kx,ay=(a[1]-p.lat)*ky,bx=(b[0]-p.lng)*kx,by=(b[1]-p.lat)*ky,dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));best=Math.min(best,Math.hypot(ax+t*dx,ay+t*dy))}return best}
 function points(p,list,range=100){if(!valid(p)||p.acc==null||!Number.isFinite(+p.acc)||p.acc>50)return;const present=new Set();for(const point of list){if(!valid(point))continue;const id=String(point.id);present.add(id);const d=distance(p,point),s=near.get(id)||{count:0,active:false,last:Infinity};if(d-p.acc>range*1.5){s.active=false;s.count=0}else if(d+p.acc<=range&&d<=s.last+3){s.count++;if(s.count>=2&&!s.active){s.active=true;emit({kind:'near',key:id,title:point.__car?'Auto vicina':'Punto vicino',message:(point.species||point.name||'Punto salvato')+' · circa '+Math.round(d)+' m'})}}else s.count=0;s.last=d;near.set(id,s)}for(const id of near.keys())if(!present.has(id))near.delete(id)}
 function protectedAreas(p,list){if(!valid(p)||p.acc==null||!Number.isFinite(+p.acc)||p.acc>50)return;for(const area of list){const inside=area.outer.some(r=>inRing(p,r))&&!area.inner.some(r=>inRing(p,r)),d=boundaryDistance(p,[...area.outer,...area.inner]);if(d<=Math.max(20,p.acc))continue;const s=areas.get(area.id)||{inside:false,count:0};if(inside){s.count++;if(s.count>=2&&!s.inside){s.inside=true;emit({kind:'protected',key:area.id,title:'Area protetta rilevata',message:area.name+' · confine OSM, verifica la cartografia ufficiale'})}}else{s.count=0;s.inside=false}areas.set(area.id,s)}}
 function territoryChange(t){const key=[t.region,t.province,t.atc].join('|');if(!t.region)return;if(territory&&territory.key!==key)emit({kind:'territory',key,title:'Cambio territorio / ATC indicativo',message:t.region+' · '+(t.atc||t.province||'ATC da verificare')+'. Verifica i confini ufficiali.'});territory={key,...t}}
 function weather(j,now=Date.now(),limits={wind:40,gust:60,rain:70}){const h=j.hourly||{},times=h.time||[],rows=times.map((t,i)=>({t:+t*1000,code:h.weather_code?.[i],wind:h.wind_speed_10m?.[i],gust:h.wind_gusts_10m?.[i],rain:h.precipitation_probability?.[i]})).filter(x=>x.t>=now-3600000&&x.t<=now+3*3600000);const c=j.current;if(c&&Number.isFinite(+c.time)&&Math.abs(+c.time*1000-now)<3600000)rows.push({t:+c.time*1000,code:c.weather_code,wind:c.wind_speed_10m,gust:c.wind_gusts_10m});const issues=[];if(rows.some(x=>[95,96,99].includes(x.code)))issues.push(['storm','Temporale previsto']);if(rows.some(x=>x.wind!=null&&x.wind>=limits.wind||x.gust!=null&&x.gust>=limits.gust))issues.push(['wind','Vento o raffiche oltre soglia']);if(rows.some(x=>x.rain!=null&&x.rain>=limits.rain))issues.push(['rain','Probabilità di pioggia almeno '+limits.rain+'%']);for(const [key,message]of issues){const old=weatherSeen.get(key);if(old==null||now-old>=3600000){weatherSeen.set(key,now);emit({kind:'weather',key,title:'Avviso meteo · prossime 3 ore',message:message+' · previsione Open-Meteo, non bollettino ufficiale'})}}}
 return {distance,valid,parseAreas,inRing,boundaryDistance,points,protectedAreas,territoryChange,weather};
}
if(typeof module!=='undefined'&&module.exports)module.exports=createPfcAlertEngine;
