(function(){
 const KEY='pfc-alert-settings-v1',LOG='pfc-alert-history-v1',q=id=>document.getElementById(id);
 let cfg={near:true,protected:true,weather:true,territory:true,vibration:true,sound:false,range:100,wind:40,gust:60,rain:70},history=[];
 try{cfg={...cfg,...JSON.parse(localStorage.getItem(KEY)||'{}')};history=JSON.parse(localStorage.getItem(LOG)||'[]').slice(0,30)}catch{}
 let audio=null,lastPosition=null,lastFixAt=0,unread=0;const statuses={gps:'Attendo GPS',protected:'Attendo GPS e rete',weather:'Attendo GPS e rete',territory:'Attendo GPS e rete'};
 const jobs={};let areaData=[],areaCenter=null,areaAt=0;
 const engine=createPfcAlertEngine(notify);
 function beep(){if(!cfg.sound||!audio||audio.state!=='running')return;try{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=660;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.22);o.start();o.stop(audio.currentTime+.22)}catch{}}
 function notify(item){if(document.hidden)return;if(!cfg[item.kind==='near'?'near':item.kind==='protected'?'protected':item.kind==='weather'?'weather':'territory'])return;const entry={...item,at:Date.now()};history.unshift(entry);history=history.slice(0,30);try{localStorage.setItem(LOG,JSON.stringify(history))}catch{}unread++;if(cfg.vibration)try{navigator.vibrate?.([80,60,80])}catch{}beep();const banner=q('pfcAlertBanner');banner.hidden=false;q('pfcAlertBannerText').textContent=item.title+' · '+item.message;clearTimeout(banner._timer);banner._timer=setTimeout(()=>banner.hidden=true,10000);render();}
 function render(){const b=q('pfcAlertsBtn');if(b)b.textContent='🔔 Avvisi'+(unread?' · '+unread:'');const s=q('pfcAlertStatus');if(s)s.textContent=[statuses.gps,...['protected','weather','territory'].map(k=>(k==='protected'?'Aree':k==='weather'?'Meteo':'Territorio')+': '+(cfg[k]?statuses[k]:'disattivati'))].join(' · ');const list=q('pfcAlertHistory');if(list)list.innerHTML=history.length?history.map(a=>'<div class="pfcAlertEntry"><b>'+esc(a.title)+'</b><small>'+new Date(a.at).toLocaleString('it-IT')+'</small><p>'+esc(a.message)+'</p></div>').join(''):'<p class="muted">Nessun avviso ricevuto.</p>';}
 function modal(){let m=q('pfcAlertsModal');if(m)return m;m=document.createElement('div');m.id='pfcAlertsModal';m.className='modal';m.innerHTML='<div class="dialog"><div class="sectionHead"><h2>🔔 Avvisi durante l’uscita</h2><button id="pfcAlertClose" class="iconBtn" aria-label="Chiudi avvisi">✕</button></div><p class="muted">Attivi con l’app aperta e GPS preciso. Meteo e nuovi confini richiedono rete. Confini OSM e ATC indicativo: verifica sempre le fonti ufficiali.</p><div id="pfcAlertStatus" class="pfcAlertStatus"></div><div class="pfcAlertSettings">'+[['near','Punti e auto vicini'],['protected','Ingresso nelle aree protette'],['weather','Temporali, pioggia e vento'],['territory','Cambio territorio / ATC indicativo'],['vibration','Vibrazione'],['sound','Suono']].map(([k,label])=>'<label><input type="checkbox" id="pfcAlert_'+k+'" '+(cfg[k]?'checked':'')+'>'+label+'</label>').join('')+'<label>Distanza di prossimità<select id="pfcAlertRange">'+[25,50,100,200].map(n=>'<option value="'+n+'" '+(cfg.range===n?'selected':'')+'>'+n+' m</option>').join('')+'</select></label><label>Vento (km/h)<input id="pfcAlertWind" type="number" min="20" max="100" value="'+cfg.wind+'"></label><label>Raffiche (km/h)<input id="pfcAlertGust" type="number" min="30" max="150" value="'+cfg.gust+'"></label><label>Pioggia (%)<input id="pfcAlertRain" type="number" min="30" max="100" value="'+cfg.rain+'"></label></div><p class="muted">Sono avvisi calcolati dalle previsioni, non allerte ufficiali della Protezione Civile. Il suono funziona dopo l’attivazione qui; la vibrazione dipende dal telefono.</p><button id="pfcAlertTest" type="button" class="secondary">Prova suono e vibrazione</button><h3>Ultimi avvisi</h3><div id="pfcAlertHistory"></div></div>';document.body.appendChild(m);q('pfcAlertClose').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};for(const key of ['near','protected','weather','territory','vibration','sound'])q('pfcAlert_'+key).onchange=async e=>{cfg[key]=e.target.checked;if(key==='sound'&&cfg.sound)await unlockAudio();saveCfg()};for(const [id,key,min,max]of [['Range','range',25,200],['Wind','wind',20,100],['Gust','gust',30,150],['Rain','rain',30,100]])q('pfcAlert'+id).onchange=e=>{const n=Number(e.target.value);if(!Number.isFinite(n)){e.target.value=cfg[key];return}cfg[key]=Math.max(min,Math.min(max,n));e.target.value=cfg[key];saveCfg()};q('pfcAlertTest').onclick=async()=>{if(cfg.sound)await unlockAudio();beep();if(cfg.vibration)navigator.vibrate?.([80,60,80]);toast('Prova avviso · suono e vibrazione secondo le impostazioni')};render();return m}
 async function unlockAudio(){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();await audio.resume()}catch{toast('Suono non disponibile su questo dispositivo')}}
 function saveCfg(){try{localStorage.setItem(KEY,JSON.stringify(cfg))}catch{}render()}
 function openPanel(){modal().classList.add('open');unread=0;render()}
 const button=document.createElement('button');button.id='pfcAlertsBtn';button.type='button';button.className='ghost';button.onclick=openPanel;document.querySelector('.topbar')?.appendChild(button);
 const banner=document.createElement('div');banner.id='pfcAlertBanner';banner.hidden=true;banner.setAttribute('role','status');banner.innerHTML='<button id="pfcAlertBannerText" type="button"></button><button id="pfcAlertDismiss" type="button" aria-label="Chiudi avviso">✕</button>';document.body.appendChild(banner);q('pfcAlertBannerText').onclick=openPanel;q('pfcAlertDismiss').onclick=()=>banner.hidden=true;
 async function json(url){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),10000);try{const r=await fetch(url,{signal:ac.signal,headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
 function eligible(kind,p,interval,movement){const j=jobs[kind]||(jobs[kind]={});const now=Date.now();if(j.busy||j.at&&now-j.at<interval&&(!j.pos||engine.distance(j.pos,p)<movement))return false;if(j.at&&now-j.at<60000)return false;j.busy=true;j.at=now;j.pos={...p};return true}
 async function protectedLoad(p){if(!cfg.protected||!eligible('protected',p,5*60000,1000))return;statuses.protected='caricamento confini locali';render();try{const dy=3/111.32,dx=3/(111.32*Math.max(.25,Math.cos(p.lat*Math.PI/180))),bbox=[p.lat-dy,p.lng-dx,p.lat+dy,p.lng+dx].join(',');const query='[out:json][timeout:8][maxsize:3500000];(way["boundary"="protected_area"]('+bbox+');relation["boundary"="protected_area"]('+bbox+');way["leisure"="nature_reserve"]('+bbox+');relation["leisure"="nature_reserve"]('+bbox+'););out geom;is_in('+p.lat+','+p.lng+')->.here;(area.here["boundary"="protected_area"];area.here["leisure"="nature_reserve"];)->.inside;rel(pivot.inside);out geom;';const j=await json('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(query));areaData=engine.parseAreas(j.elements);areaCenter={...p};areaAt=Date.now();statuses.protected=areaData.length?areaData.length+' confini OSM disponibili':'nessun confine restituito · copertura non garantita';if(cfg.protected&&lastPosition&&engine.distance(lastPosition,p)<2000)engine.protectedAreas(lastPosition,areaData)}catch{statuses.protected='rete non disponibile · verifica non aggiornata'}finally{jobs.protected.busy=false;render()}}
 async function weatherLoad(p){if(!cfg.weather||!eligible('weather',p,15*60000,5000))return;statuses.weather='caricamento previsioni';render();try{const j=await json('https://api.open-meteo.com/v1/forecast?latitude='+p.lat+'&longitude='+p.lng+'&current=weather_code,wind_speed_10m,wind_gusts_10m&hourly=weather_code,precipitation_probability,wind_speed_10m,wind_gusts_10m&wind_speed_unit=kmh&timeformat=unixtime&forecast_days=2');if(cfg.weather&&lastPosition&&engine.distance(lastPosition,p)<5000)engine.weather(j,Date.now(),cfg);statuses.weather='aggiornato '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}catch{statuses.weather='rete non disponibile · previsione non aggiornata'}finally{jobs.weather.busy=false;render()}}
 async function territoryLoad(p){if(!cfg.territory||!eligible('territory',p,5*60000,1000))return;try{const result=await window.__PFC_TERRITORY_REFRESH__?.();statuses.territory=result?'aggiornato · ATC indicativo':'non aggiornato · verifica manuale'}finally{jobs.territory.busy=false;render()}}
 function onPosition(p){if(document.hidden||!engine.valid(p))return;lastPosition={...p};lastFixAt=Date.now();statuses.gps=p.acc==null||!Number.isFinite(+p.acc)||p.acc>50?'GPS poco preciso · avvisi di posizione sospesi':'GPS ±'+Math.round(p.acc)+' m';if(p.acc!=null&&Number.isFinite(+p.acc)&&p.acc<=50){const mode=(()=>{try{return JSON.parse(localStorage.getItem('pfc-v661-settings')||'{}').mode}catch{return 'hunt'}})();const list=(state.points||[]).filter(x=>mode==='mushroom'?x.sightingKind==='mushroom':x.sightingKind!=='mushroom');if(state.car)list.push({...state.car,id:'__car__',name:'Auto parcheggiata',__car:true});if(cfg.near)engine.points(p,list,cfg.range);if(cfg.protected&&areaCenter&&Date.now()-areaAt<30*60000&&engine.distance(areaCenter,p)<2000)engine.protectedAreas(p,areaData);Promise.allSettled([protectedLoad(p),weatherLoad(p),territoryLoad(p)]);}render()}
 window.addEventListener('pfc:position',e=>onPosition(e.detail));window.addEventListener('pfc:territory',e=>{window.__PFC_TERRITORY_LAST__=e.detail;if(cfg.territory&&Date.now()-lastFixAt<120000)engine.territoryChange(e.detail)});
 setInterval(()=>{if(document.hidden)return;if(Date.now()-lastFixAt>60000){statuses.gps='GPS da aggiornare · avvisi di posizione sospesi';render();return}if(lastPosition)Promise.allSettled([protectedLoad(lastPosition),weatherLoad(lastPosition),territoryLoad(lastPosition)])},30000);
 window.__PFC_ALERT_STATUS__=()=>({version:'6.8.0',settings:{...cfg},statuses:{...statuses},count:history.length});render();if(lastPos)onPosition(lastPos);
})();
