// V6.6.4 - radar orizzontale stabile: ignora su/giu e inclinazioni, usa solo rotazione sul piano
(function(){
  const VER='6.8.0';
  const q=id=>document.getElementById(id);
  const norm=n=>((n%360)+360)%360;
  const adiff=(a,b)=>Math.abs((((a-b)+540)%360)-180);
  const smooth=(a,b,f=.18)=>{if(a==null)return b;const d=(((b-a)+540)%360)-180;return norm(a+d*f)};
  const distKm=(a,b)=>{const R=6371,r=Math.PI/180,d1=(b.lat-a.lat)*r,d2=(b.lng-a.lng)*r,x=Math.sin(d1/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
  const bear=(a,b)=>{const r=Math.PI/180,p1=a.lat*r,p2=b.lat*r,dl=(b.lng-a.lng)*r;return norm(Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))/r)};
  let open=false,heading=null,stream=null,lastSample=null,stableCount=0,absoluteSeenAt=0,jumpCandidate=null;
  const prevDist=new Map(); let cameraEpoch=0;
  function ensureCss(){if(q('ct664Css'))return;const s=document.createElement('style');s.id='ct664Css';s.textContent=`
#ctRadar664{z-index:3000}.ct664Dialog{background:linear-gradient(155deg,#152f24,#091a14);color:#f2f8f1;max-width:620px;border:1px solid #80b59640}.ct664Dialog h2{font-size:24px;margin:0 0 5px}.ct664Dialog .sectionHead{margin-bottom:14px}.ct664Stage{position:relative;height:min(48vh,390px);min-height:260px;border-radius:24px;overflow:hidden;background:radial-gradient(ellipse at center,#214c39,#0a1b17 72%);border:1px solid #77c39735}.ct664Video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.6;visibility:hidden;pointer-events:none}.ct664Video::-webkit-media-controls,.ct664Video::-webkit-media-controls-start-playback-button{display:none!important}.ct679Scope{position:absolute;width:72%;max-width:300px;aspect-ratio:1;left:50%;top:48%;transform:translate(-50%,-50%);border-radius:50%;border:1px solid #9fe5be70;background:repeating-radial-gradient(circle,transparent 0 24%,#89c9a42c 24.5% 25%,transparent 25.5% 49%);box-shadow:0 0 35px #72c89e12,inset 0 0 32px #78daa516;pointer-events:none}.ct679Scope:before{content:'';position:absolute;inset:0;border-radius:50%;background:conic-gradient(from -24deg, #78efb344 0deg, #b0f8c930 48deg,transparent 48deg 360deg)}.ct679Scope:after{content:'';position:absolute;left:50%;top:50%;width:9px;height:9px;transform:translate(-50%,-50%);border-radius:50%;background:#d4ffdf;box-shadow:0 0 0 6px #b5f9d019,0 0 20px #92fac9}.ct664Reticle{position:absolute;inset:0;pointer-events:none}.ct664Reticle:before{content:'';position:absolute;left:50%;top:0;bottom:0;width:1px;background:#9bdcbb40}.ct664Reticle:after{content:'';position:absolute;top:50%;left:0;right:0;height:1px;background:#9bdcbb40}.ct679Forward{position:absolute;top:-18px;left:50%;transform:translateX(-50%);font-size:10px;letter-spacing:2px;color:#c6e8d1}.ct679Range{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);font-size:10px;color:#b8d6c5;white-space:nowrap;letter-spacing:1px}.ct664Deg{position:absolute;left:50%;top:12px;transform:translateX(-50%);background:#092119df;border:1px solid #9ddeba40;padding:6px 16px;border-radius:999px;font-size:24px;font-weight:800;letter-spacing:1px}.ct664State{position:absolute;left:12px;right:12px;bottom:12px;background:#0a201be8;padding:10px;border-radius:14px;font-size:12px;text-align:center;border:1px solid #80b59630}.ct679CameraStatus{font-size:11px;color:#a8c6b4;margin:8px 2px}.ct664List{display:grid;gap:8px;margin-top:10px;max-height:30vh;overflow:auto}.ct664Item{background:#ffffff08;border:1px solid #ffffff1c;border-radius:16px;padding:14px}.ct664Item b{display:block;font-size:16px;margin-bottom:4px}.ct664Item span{font-size:13px;color:#c7dacf}.ct664Away{font-size:11px;color:#f0c98b}.ct664Ready{color:#b8f0c7}.ct664Hold{color:#ffd58b}
`;document.head.appendChild(s)}
  function modal(){let m=q('ctRadar664');if(m)return m;ensureCss();m=document.createElement('div');m.id='ctRadar664';m.className='modal';m.innerHTML=`<div class="dialog ct664Dialog"><div class="sectionHead"><div><h2>◎ Radar punti</h2><div class="muted" style="color:#b4cdbf;font-size:12px">Tieni il telefono piatto e ruota lentamente.</div></div><button id="ct664Close" class="iconBtn" type="button" aria-label="Chiudi radar">✕</button></div><div class="ct664Stage"><video id="ct664Video" class="ct664Video" autoplay playsinline muted aria-hidden="true"></video><div class="ct679Scope" aria-hidden="true"><div class="ct664Reticle"></div><span class="ct679Forward">DIREZIONE</span><span class="ct679Range">10 KM · ±24°</span></div><div id="ct664Deg" class="ct664Deg">—°</div><div id="ct664State" class="ct664State">Attendo sensore…</div></div><div id="ct679CameraStatus" class="ct679CameraStatus">Radar direzionale · avvio fotocamera…</div><div class="muted" style="color:#b4cdbf;margin-top:8px;font-size:12px">Punti entro 10 km nella direzione del telefono. Se ti allontani, la distanza viene nascosta.</div><div id="ct664List" class="ct664List"></div></div>`;document.body.appendChild(m);q('ct664Close').onclick=closeRadar;m.onclick=e=>{if(e.target===m)closeRadar()};return m}
  async function startCamera(){
    const epoch=++cameraEpoch,v=q('ct664Video'),st=q('ct679CameraStatus');
    v.style.visibility='hidden';st.textContent='Radar direzionale · avvio fotocamera…';
    const hide=()=>{if(epoch!==cameraEpoch)return;v.style.visibility='hidden';st.textContent='Vista radar · fotocamera non attiva'};
    const show=()=>{if(epoch!==cameraEpoch||!open)return;if(v.readyState>=2&&v.videoWidth>0&&!v.paused){v.style.visibility='visible';st.textContent='Fotocamera attiva · radar sovrapposto'}};
    v.onplaying=show;v.onloadeddata=show;v.onpause=hide;v.onerror=hide;v.onemptied=hide;v.onwaiting=hide;
    let candidate;
    try{
      if(!navigator.mediaDevices?.getUserMedia)throw Error('Fotocamera non disponibile');
      candidate=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
      if(!open||epoch!==cameraEpoch){candidate.getTracks().forEach(t=>t.stop());return}
      stream=candidate;v.srcObject=stream;await v.play();show();
      setTimeout(()=>{if(open&&epoch===cameraEpoch&&v.style.visibility!=='visible')hide()},3000);
    }catch(e){if(candidate)candidate.getTracks().forEach(t=>t.stop());if(epoch===cameraEpoch){stream=null;v.srcObject=null;hide();st.textContent='Vista radar · fotocamera non disponibile';}}
  }
  function screenAngle(){try{return Number(screen.orientation?.angle||window.orientation||0)||0}catch{return 0}}
  function rawHeading(e){if(Number.isFinite(+e.webkitCompassHeading))return norm(+e.webkitCompassHeading);if(!Number.isFinite(+e.alpha))return null;return norm(360-(+e.alpha)+screenAngle())}
  function setState(txt,cls){const e=q('ct664State');if(!e)return;e.className='ct664State '+(cls||'');e.textContent=txt}
  function acceptRaw(raw,now){if(heading==null){heading=raw;jumpCandidate=null;return true}const d=adiff(raw,heading);if(d<1.2)return false;if(d>42){if(!jumpCandidate||adiff(jumpCandidate.raw,raw)>7||now-jumpCandidate.at>700){jumpCandidate={raw,at:now,count:1};return false}jumpCandidate.count++;if(jumpCandidate.count<3)return false;jumpCandidate=null;heading=smooth(heading,raw,.32);return true}jumpCandidate=null;heading=smooth(heading,raw,d>18?.28:.16);return true}
  function orientation(e){if(!open)return;const now=performance.now();if(e.type==='deviceorientationabsolute')absoluteSeenAt=now;else if(now-absoluteSeenAt<1400)return;const beta=Number(e.beta),gamma=Number(e.gamma),raw=rawHeading(e);if(!Number.isFinite(beta)||!Number.isFinite(gamma)||raw==null)return;const flat=Math.abs(beta)<=12&&Math.abs(gamma)<=12;if(!flat){stableCount=0;lastSample={beta,gamma,raw,at:now};setState('📱 Direzione bloccata: rimetti il telefono piatto','ct664Hold');return}if(lastSample){const tiltMove=Math.hypot(beta-lastSample.beta,gamma-lastSample.gamma);if(tiltMove>1.8){stableCount=0;lastSample={beta,gamma,raw,at:now};setState('⏸ Inclinazione rilevata: direzione congelata','ct664Hold');return}}stableCount++;lastSample={beta,gamma,raw,at:now};if(stableCount<3){setState('Mantieni il telefono piatto…','ct664Hold');return}if(acceptRaw(raw,now)){setState('✅ Piatto · ruota a sinistra/destra','ct664Ready');render()}}
  function render(){const deg=q('ct664Deg'),list=q('ct664List');if(!list)return;if(heading==null){if(deg)deg.textContent='—°';list.innerHTML='<div class="ct664Item">Attendo una rotazione orizzontale stabile.</div>';return}if(deg)deg.textContent=Math.round(heading)+'°';const o=lastPos;if(!o){list.innerHTML='<div class="ct664Item">GPS non disponibile.</div>';return}let mode='hunt';try{mode=JSON.parse(localStorage.getItem('pfc-v661-settings')||'{}').mode||'hunt'}catch{}const src=(state.points||[]).filter(p=>mode==='mushroom'?p.sightingKind==='mushroom':p.sightingKind!=='mushroom');if(state.car&&Number.isFinite(+state.car.lat)&&Number.isFinite(+state.car.lng))src.push({id:'__car__',lat:+state.car.lat,lng:+state.car.lng,name:'Auto parcheggiata',type:'Parcheggio',__car:true});const arr=src.map(p=>{const d=distKm(o,{lat:+p.lat,lng:+p.lng}),b=bear(o,{lat:+p.lat,lng:+p.lng});return{p,d,b,delta:adiff(b,heading)}}).filter(x=>Number.isFinite(x.d)&&x.d<=10&&x.delta<=24).sort((a,b)=>a.d-b.d);if(!arr.length){list.innerHTML='<div class="ct664Item"><b>Nessun punto in questa direzione</b><span>Ruota lentamente sul piano.</span></div>';return}list.innerHTML=arr.slice(0,8).map(x=>{const old=prevDist.get(x.p.id),away=old!=null&&x.d-old>0.02;prevDist.set(x.p.id,x.d);const label=x.p.species||x.p.name||x.p.type||'Punto',ico=x.p.__car?'🚗':x.p.sightingKind==='mushroom'?'🍄':x.p.type==='Avvistamento'?'🕊':'📍',d=x.d<1?Math.round(x.d*1000)+' m':x.d.toFixed(1)+' km';return `<div class="ct664Item"><b>${ico} ${esc(label)}</b><span>Direzione ${Math.round(x.b)}° · scarto ${Math.round(x.delta)}°</span>${away?'<div class="ct664Away">↩ Ti stai allontanando · distanza nascosta</div>':`<div style="font-size:18px;font-weight:900;margin-top:3px">${d}</div>`}</div>`}).join('')}
  function resetOrientation(){heading=null;lastSample=null;stableCount=0;jumpCandidate=null;setState('Orientamento cambiato · tieni il telefono piatto','ct664Hold');render()}
  async function openRadar(){if(!lastPos){try{const p=await getFix?.();if(p)lastPos=p}catch{}}if(!lastPos)return toast('Serve il GPS per usare il radar');modal().classList.add('open');open=true;heading=null;lastSample=null;stableCount=0;jumpCandidate=null;prevDist.clear();setState('Attendo sensore…');render();startCamera();try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const r=await DeviceOrientationEvent.requestPermission();if(r!=='granted')throw Error('Permesso orientamento negato')}}catch(e){toast(e.message||'Sensore orientamento non disponibile')}if(!open)return;window.addEventListener('deviceorientationabsolute',orientation,true);window.addEventListener('deviceorientation',orientation,true);screen.orientation?.addEventListener?.('change',resetOrientation);render()}
  function closeRadar(){open=false;cameraEpoch++;q('ctRadar664')?.classList.remove('open');window.removeEventListener('deviceorientationabsolute',orientation,true);window.removeEventListener('deviceorientation',orientation,true);screen.orientation?.removeEventListener?.('change',resetOrientation);try{stream?.getTracks?.().forEach(t=>t.stop())}catch{}stream=null;const v=q('ct664Video');if(v){v.style.visibility='hidden';v.srcObject=null}}
  function wire(){const b=q('ctRadarBtn');if(b){b.onclick=openRadar;b.title=`Radar orizzontale stabile v${VER}`}const old=q('ctRadarModal');if(old)old.remove()}
  function boot(){if(q('ctRadarBtn')){wire();return}let n=0,t=setInterval(()=>{n++;if(q('ctRadarBtn')){clearInterval(t);wire()}else if(n>40)clearInterval(t)},150)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
