/* Visible per-sighting wind comparisons, independent of Caccia/Funghi mode. */
(()=>{'use strict';
const q=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const results=new Map();let api,modalPoint=null,request=0;
const clock=(t,tz)=>new Date(t*1000).toLocaleString('it-IT',{timeZone:tz,day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
const describe=s=>s.speed<3?'Calma / vento debole · '+s.speed.toFixed(1)+' km/h':PFC_WIND_ENGINE.windName(s.dir)+' · '+Math.round(s.dir)+'° · '+s.speed.toFixed(1)+' km/h';
function html(z){if(z.error)return '<p class="pfcWindMissing">'+esc(z.error)+'</p>';const {now,base,similar,change,knownUntil,gap,timezone,similarUntil}=z;
 return '<div class="'+(similar===true?'pfcWindGood':similar===false?'pfcWindDifferent':'pfcWindMissing')+'"><b>'+(similar===true?'● VENTO SIMILE A QUELLO SALVATO':similar===false?'● VENTO DIVERSO DA QUELLO SALVATO':'Vento salvato insufficiente per il confronto')+'</b></div><p><strong>💨 '+esc(describe(now))+'</strong>'+ (now.gust!=null?' · Raffiche '+now.gust.toFixed(1)+' km/h':'')+'<br><small>Dato delle '+clock(now.time,timezone)+'</small></p>'+(base.dir!=null&&base.speed!=null?'<p class="note">Al salvataggio: '+esc(describe(base))+'</p>':'')+
 (change?'<p><b>↪ Possibile cambio dalle '+clock(change.time,timezone)+'</b><br>'+esc(describe(change))+(change.gust!=null?' · raffiche '+change.gust.toFixed(1)+' km/h':'')+'</p>':'<p><b>'+(knownUntil>now.time?'Vento previsto stabile fino alle '+clock(knownUntil,timezone):'Stabilità futura non valutabile')+'</b></p>')+
 (similar===true&&similarUntil>now.time?'<p class="note">Vento simile a quello salvato nelle ore verificate fino alle '+clock(similarUntil,timezone)+'.</p>':'')+(gap?'<p class="note">Sono presenti ore senza dati: la verifica si ferma all’ultima ora disponibile.</p>':'')+'<p class="note">Orari previsti, con dettaglio orario. Un cambio significativo è una rotazione di almeno 45°, una variazione di almeno 10 km/h, di 15 km/h nelle raffiche o il passaggio da/a calma. Le condizioni reali possono variare.</p>';
}
async function forecast(p,target){
 const d=new Date(target*1000),day=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),next=new Date(d);next.setDate(next.getDate()+1);const end=next.getFullYear()+'-'+String(next.getMonth()+1).padStart(2,'0')+'-'+String(next.getDate()).padStart(2,'0');
 const url=new URL('https://api.open-meteo.com/v1/forecast');Object.entries({latitude:p.lat,longitude:p.lng,hourly:'wind_speed_10m,wind_direction_10m,wind_gusts_10m',current:'wind_speed_10m,wind_direction_10m,wind_gusts_10m',wind_speed_unit:'kmh',timezone:'auto',timeformat:'unixtime',start_date:day,end_date:end}).forEach(([k,v])=>url.searchParams.set(k,v));
 const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),15000);try{const r=await fetch(url,{cache:'no-store',signal:ac.signal});if(!r.ok)throw Error('Previsione non disponibile per questa data.');return PFC_WIND_ENGINE.analyze(await r.json(),p,target);}finally{clearTimeout(timer);}
}
function target(date,time){const n=new Date(date+'T'+time+':00').getTime()/1000;if(!Number.isFinite(n))throw Error('Scegli giorno e ora validi.');return n;}
function setNow(prefix){const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString();q(prefix+'Date').value=local.slice(0,10);q(prefix+'Time').value=local.slice(11,16);}
function panel(){if(q('pfcWindModal'))return;const m=document.createElement('div');m.id='pfcWindModal';m.className='modal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML='<div class="dialog"><div class="sectionHead"><h2>💨 Confronta vento</h2><button id="pfcWindClose" class="iconBtn" aria-label="Chiudi confronto vento">✕</button></div><p id="pfcWindPoint"></p><div class="ctSightGrid"><label>Giorno<input id="pfcWindDate" type="date"></label><label>Ora<input id="pfcWindTime" type="time"></label></div><p class="note">Selezione nell’orario del telefono. I risultati indicano l’orario locale del punto.</p><button id="pfcWindRun" class="primary wide">Confronta vento e cerca il prossimo cambio</button><div id="pfcWindOutput" role="status"></div></div>';document.body.appendChild(m);q('pfcWindClose').onclick=()=>{request++;m.classList.remove('open');q('pfcWindRun').disabled=false;};q('pfcWindRun').onclick=async()=>{const stamp=++request,p=modalPoint;if(!p)return;q('pfcWindRun').disabled=true;q('pfcWindOutput').textContent='Controllo vento e ore successive…';try{const z=await forecast(p,target(q('pfcWindDate').value,q('pfcWindTime').value));results.set(p.id,z);decorate();if(stamp===request)q('pfcWindOutput').innerHTML=html(z);}catch(e){if(stamp===request)q('pfcWindOutput').textContent=e.name==='AbortError'?'La previsione non risponde. Riprova.':e.message;}finally{if(stamp===request)q('pfcWindRun').disabled=false;}};setNow('pfcWind');}
function open(id){const p=api?.points().find(p=>p.id===id);if(!p)return;panel();modalPoint=p;request++;q('pfcWindRun').disabled=false;q('pfcWindPoint').textContent=p.species||p.name||'Avvistamento';setNow('pfcWind');q('pfcWindOutput').innerHTML=results.has(id)?html(results.get(id)):'';q('pfcWindModal').classList.add('open');}
async function all(){const button=q('ctSightingRun'),out=q('ctSightingSummary');if(!button||!out)return;button.disabled=true;try{const t=target(q('ctSightingDate').value,q('ctSightingTime').value),pts=api.points().filter(p=>p.type==='Avvistamento'&&p.sightingKind!=='mushroom'&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng)));let good=0;for(let i=0;i<pts.length;i++){out.textContent='Confronto vento '+(i+1)+' di '+pts.length+'…';try{const z=await forecast(pts[i],t);results.set(pts[i].id,z);if(z.similar===true)good++;}catch(e){results.set(pts[i].id,{error:e.name==='AbortError'?'Previsione non raggiungibile. Riprova.':e.message});}decorate();}out.textContent=pts.length?good+' avvistamenti con vento simile su '+pts.length+'. I dettagli del cambio sono sotto ogni avvistamento.':'Nessun avvistamento salvato.';}catch(e){out.textContent=e.message;}finally{button.disabled=false;}}
function decorate(){
 const host=q('historyList');if(!host||!api)return;try{if(JSON.parse(localStorage.getItem('pfc-v661-settings')||'{}').mode==='mushroom')return;}catch{}const run=q('ctSightingRun');if(run){if(run.textContent!=='💨 Confronta vento di tutti gli avvistamenti')run.textContent='💨 Confronta vento di tutti gli avvistamenti';run.onclick=all;const box=q('ctSightingCheck');const intro=box.querySelector('.muted');if(intro&&intro.textContent!=='Confronta vento salvato, vento previsto e ora del prossimo cambio.')intro.textContent='Confronta vento salvato, vento previsto e ora del prossimo cambio.';}
 host.querySelectorAll('button[onclick]').forEach(button=>{const match=(button.getAttribute('onclick')||'').match(/CT\.openHistoryPoint\('([^']+)'\)/);if(!match)return;const id=match[1],row=button.closest('.rowBtns'),item=button.closest('.item');if(!row||!item)return;if(!row.querySelector('[data-wind-point]')){const b=document.createElement('button');b.type='button';b.className='mini pfcWindButton';b.textContent='💨 Confronta vento';b.dataset.windPoint=id;b.onclick=()=>open(id);row.prepend(b);}if(results.has(id)){let box=item.querySelector('.pfcWindResult');if(!box){box=document.createElement('div');box.className='pfcWindResult';row.insertAdjacentElement('beforebegin',box);}const content=html(results.get(id));if(box.innerHTML!==content)box.innerHTML=content;}});
}
function boot(){if(api||!window.__PFC_LIVE_API__)return;api=window.__PFC_LIVE_API__;const css=document.createElement('style');css.textContent='.pfcWindButton{background:#dcefe5!important;color:#173f2b!important;font-weight:850!important}.pfcWindResult{margin:10px 0;padding:12px;border:1px solid #c8ded0;border-radius:12px;font-size:13px}.pfcWindGood{color:#176135}.pfcWindDifferent{color:#a33b23}.pfcWindMissing{color:#74603c}#pfcWindOutput{margin-top:14px}#pfcWindOutput p{margin:9px 0}';document.head.appendChild(css);new MutationObserver(decorate).observe(q('page-diary'),{childList:true,subtree:true});decorate();window.PFC_WIND_UI={open,all};}
window.addEventListener('pfc:ready',boot);boot();
})();
