const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),{webcrypto:crypto}=require('node:crypto');
const nodes=new Map(),events={},tracked=[],presence={};let channel,sync,subscription,connects=0,frames=0,mapShows=0;const storage=new Map(),persistent=new Map(),nativeCommands=[];let readyTransport;const sessionStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
class El{constructor(id){this.hidden=false;this.value='';this.classList={add(){},remove(){}};if(id)nodes.set(id,this);}set innerHTML(v){this.html=v;for(const m of v.matchAll(/id="([^"]+)"/g))new El(m[1]);}get innerHTML(){return this.html||'';}querySelectorAll(){return [];}appendChild(){}setAttribute(){}select(){}}
['pfc676Quick','page-backup'].forEach(id=>new El(id));
const dispatch=e=>{for(const f of events[e.type]||[])f(e);};
const ctx={sessionStorage,setTimeout,clearTimeout,crypto,TextEncoder,TextDecoder,btoa,atob,URLSearchParams,location:{origin:'https://example.test',pathname:'/app/',hash:'',search:''},history:{replaceState(){}},localStorage:{length:0,key(){},getItem:k=>persistent.get(k),setItem:(k,v)=>persistent.set(k,v),removeItem:k=>persistent.delete(k)},navigator:{onLine:true},setInterval:()=>1,clearInterval(){},console};
ctx.document={hidden:false,head:new El(),body:new El(),getElementById:id=>nodes.get(id),createElement:()=>new El(),addEventListener:(n,f)=>(events[n]??=[]).push(f)};ctx.window=ctx;ctx.addEventListener=(n,f)=>(events[n]??=[]).push(f);ctx.dispatchEvent=dispatch;ctx.Event=class{constructor(type){this.type=type;}};ctx.CustomEvent=class extends ctx.Event{constructor(type,opt){super(type);this.detail=opt.detail;}};
const marker={addTo(){return this;},bindTooltip(){},setLatLng(){},setTooltipContent(){},setIcon(){}};ctx.L={layerGroup:()=>({addTo(){return this;},removeLayer(){}}),marker:()=>({...marker}),divIcon:()=>({}),latLngBounds:points=>points};
ctx.__PFC_LIVE_API__={map:()=>({setView(){},hasLayer(){return true;},fitBounds(){frames++;}}),getFix:async()=>null,showMap(){mapShows++;}};
ctx.supabase={createClient:()=>({removeChannel:async()=>{},channel:(room)=>{connects++;channel={room,on(kind,opt,fn){if(kind==='presence')sync=fn;return this;},subscribe(fn){subscription=fn;fn('SUBSCRIBED');return this;},presenceState:()=>presence,track:async p=>{tracked.push(p);presence.self=[p];await sync();return 'ok';},untrack:async()=>{delete presence.self;await sync();},send:async()=> 'ok'};return channel;}})};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('cacciatraccia/native-team-6.9.9.js','utf8'),ctx);events['pfc:team-ready']=[e=>readyTransport=e.detail];vm.runInContext(fs.readFileSync('cacciatraccia/friends-6.9.8-reconnect.js','utf8'),ctx);
const flush=async()=>{for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));};
(async()=>{nodes.get('pfcFriendsName').value='Mario';await nodes.get('pfcFriendsCreate').onclick();await flush();assert(mapShows>0,'configuration returns to map');assert(storage.has('pfc-active-outing'),'group restored on reload');assert(tracked.length>0,'join must publish membership without GPS');assert(persistent.has('pfc-active-outing'));const nativePort={postMessage:s=>nativeCommands.push(JSON.parse(s)),start(){},close(){}};dispatch({type:'message',origin:'https://untrusted.test',source:null,data:'pfc-native-team-v1',ports:[nativePort]});assert.equal(ctx.__PFC_NATIVE_TEAM__.available,false,'reject untrusted origin');dispatch({type:'message',origin:'',source:null,data:'pfc-native-team-v1',ports:[nativePort]});assert(ctx.__PFC_NATIVE_TEAM__.available);assert(nativeCommands.some(c=>c.command==='start'),'a delayed native bridge starts the already configured group');nativePort.onmessage({data:JSON.stringify({event:'state',active:true})});await flush();assert(nodes.get('teamMemberCount').textContent.includes('1 persona'));
const token=new URLSearchParams(nodes.get('pfcFriendsInvite').value.split('#')[1]).get('uscita'),secret=token.split('.')[0],key=await crypto.subtle.importKey('raw',Buffer.from(secret,'base64url'),'AES-GCM',false,['encrypt','decrypt']);
async function packet(p){const iv=crypto.getRandomValues(new Uint8Array(12)),raw=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(channel.room)},key,new TextEncoder().encode(JSON.stringify(p)));return {packet:{iv:Buffer.from(iv).toString('base64url'),data:Buffer.from(raw).toString('base64url')}};}
const id='abcdefghijklmnopqrstuv';presence.luca=[await packet({id,name:'Luca',memberAt:Date.now()})];await sync();assert(nodes.get('teamMemberCount').textContent.includes('2 persone'));assert(nodes.get('teamMembers').innerHTML.includes('Luca'));assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0,'GPS absent member must not appear at fabricated coordinates');
presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.45,lng:15.55,acc:10,at:Date.now()})];await sync();assert.equal(ctx.__PFC_FRIEND_POINTS__()[0].name,'Luca');assert.equal(ctx.__PFC_FRIEND_POINTS__()[0].lat,41.45);assert.equal(frames,1,'first companion frames map');ctx.__PFC_SHOW_TEAM_MAP__();assert.equal(frames,2,'explicit show all frames map');const oldSubscription=subscription;const beforeShows=mapShows;subscription('TIMED_OUT');assert(nodes.get('teamMemberCount').textContent.includes('2 persone'),'retain known members during reconnect');await new Promise(r=>setTimeout(r,1700));await flush();assert(connects>=2,'failed socket recreated');assert.equal(mapShows,beforeShows,'reconnect does not force group panel/map navigation');oldSubscription('CHANNEL_ERROR');assert(!nodes.get('pfcFriendsStatus').textContent.includes('interrotta'),'ignore obsolete channel callback');ctx.navigator.onLine=false;dispatch({type:'offline'});assert(nodes.get('pfcFriendsList').innerHTML.includes('Ultima posizione'),'offline event labels immediately');assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0);ctx.navigator.onLine=true;dispatch({type:'online'});await flush();
ctx.document.hidden=true;nativePort.onmessage({data:JSON.stringify({event:'position',lat:41.4,lng:15.6,acc:7,at:Date.now()})});dispatch({type:'visibilitychange'});await flush();const hiddenPacket=tracked.at(-1).packet;const hiddenFix=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(hiddenPacket.iv,'base64url'),additionalData:new TextEncoder().encode(channel.room)},key,Buffer.from(hiddenPacket.data,'base64url'))));assert.equal(hiddenFix.lat,41.4,'native fresh GPS is shared while hidden');const realNow=Date.now,FutureDate=class extends Date{static now(){return realNow()+9*3600000;}};ctx.Date=FutureDate;assert(readyTransport.ready(),'an accepted connection continues after invitation expiry until explicitly stopped');ctx.Date=Date;ctx.document.hidden=false;await nodes.get('pfcFriendsPause').onclick();await flush();const own=tracked.at(-1).packet;const plain=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(own.iv,'base64url'),additionalData:new TextEncoder().encode(channel.room)},key,Buffer.from(own.data,'base64url'))));assert.equal(plain.name,'Mario');assert.equal(plain.lat,undefined,'pause must retain membership while removing location');
presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.45,lng:15.55,acc:10,at:Date.now()-31000})];await sync();assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0,'stale position must be removed from radar');assert(nodes.get('pfcFriendsList').innerHTML.includes('Ultima posizione'),'stale GPS retained and explicitly labelled');delete presence.luca;await sync();assert(nodes.get('pfcFriendsList').innerHTML.includes('Luca'),'disconnected peer point retained');assert(nodes.get('pfcFriendsList').innerHTML.includes('Ultima posizione'));assert(nodes.get('teamMemberCount').textContent.includes('2 persone'),'offline member retained separately from live presence');
 presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.46,lng:15.56,acc:8,at:Date.now(),sharing:true})];await sync();assert.equal(ctx.__PFC_FRIEND_POINTS__()[0].lat,41.46,'reconnection restores fresh position');assert(!nodes.get('pfcFriendsList').innerHTML.includes('Ultima posizione'),'fresh point restores live label');
 presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),sharing:false})];await sync();assert(!nodes.get('pfcFriendsList').innerHTML.includes('Luca'),'explicit sharing pause removes cached location');
 presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.46,lng:15.56,acc:8,at:Date.now(),sharing:true})];await sync();nativePort.onmessage({data:JSON.stringify({event:'stop'})});await flush();assert(!persistent.has('pfc-active-outing'),'notification stop clears persistent membership');assert(nativeCommands.some(c=>c.command==='stop'),'explicit exit stops native service');assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0);assert(!nodes.get('pfcFriendsList').innerHTML.includes('Luca'),'exit clears retained points');
console.log('PASS native background bridge + last GPS: retain offline/stale map points with timestamp, exclude from live radar, reconnect restores live coordinates, explicit pause/exit clears cache. Mock transport, real AES-GCM.');})().catch(e=>{console.error(e);process.exit(1);});
