const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict'),{webcrypto:crypto}=require('node:crypto');
const nodes=new Map(),events={},tracked=[],presence={};let channel,sync;
class El{constructor(id){this.hidden=false;this.value='';this.classList={add(){},remove(){}};if(id)nodes.set(id,this);}set innerHTML(v){this.html=v;for(const m of v.matchAll(/id="([^"]+)"/g))new El(m[1]);}get innerHTML(){return this.html||'';}querySelectorAll(){return [];}appendChild(){}setAttribute(){}select(){}}
['pfc676Quick','page-backup'].forEach(id=>new El(id));
const dispatch=e=>{for(const f of events[e.type]||[])f(e);};
const ctx={crypto,TextEncoder,TextDecoder,btoa,atob,URLSearchParams,location:{origin:'https://example.test',pathname:'/app/',hash:'',search:''},history:{replaceState(){}},localStorage:{length:0,key(){},getItem(){return null;},setItem(){},removeItem(){}},navigator:{onLine:true},setInterval:()=>1,clearInterval(){},console};
ctx.document={hidden:false,head:new El(),body:new El(),getElementById:id=>nodes.get(id),createElement:()=>new El(),addEventListener:(n,f)=>(events[n]??=[]).push(f)};ctx.window=ctx;ctx.addEventListener=(n,f)=>(events[n]??=[]).push(f);ctx.dispatchEvent=dispatch;ctx.Event=class{constructor(type){this.type=type;}};ctx.CustomEvent=class extends ctx.Event{constructor(type,opt){super(type);this.detail=opt.detail;}};
const marker={addTo(){return this;},bindTooltip(){},setLatLng(){},setTooltipContent(){}};ctx.L={layerGroup:()=>({addTo(){return this;},removeLayer(){}}),marker:()=>({...marker}),divIcon:()=>({})};
ctx.__PFC_LIVE_API__={map:()=>({setView(){}}),getFix:async()=>null,showMap(){}};
ctx.supabase={createClient:()=>({removeChannel:async()=>{},channel:(room)=>{channel={room,on(kind,opt,fn){if(kind==='presence')sync=fn;return this;},subscribe(fn){fn('SUBSCRIBED');return this;},presenceState:()=>presence,track:async p=>{tracked.push(p);presence.self=[p];await sync();return 'ok';},untrack:async()=>{delete presence.self;await sync();},send:async()=> 'ok'};return channel;}})};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('cacciatraccia/friends-6.9.7.js','utf8'),ctx);
const flush=async()=>{for(let i=0;i<20;i++)await new Promise(r=>setImmediate(r));};
(async()=>{nodes.get('pfcFriendsName').value='Mario';await nodes.get('pfcFriendsCreate').onclick();await flush();assert(tracked.length>0,'join must publish membership without GPS');assert(nodes.get('teamMemberCount').textContent.includes('1 persona'));
const token=new URLSearchParams(nodes.get('pfcFriendsInvite').value.split('#')[1]).get('uscita'),secret=token.split('.')[0],key=await crypto.subtle.importKey('raw',Buffer.from(secret,'base64url'),'AES-GCM',false,['encrypt','decrypt']);
async function packet(p){const iv=crypto.getRandomValues(new Uint8Array(12)),raw=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(channel.room)},key,new TextEncoder().encode(JSON.stringify(p)));return {packet:{iv:Buffer.from(iv).toString('base64url'),data:Buffer.from(raw).toString('base64url')}};}
const id='abcdefghijklmnopqrstuv';presence.luca=[await packet({id,name:'Luca',memberAt:Date.now()})];await sync();assert(nodes.get('teamMemberCount').textContent.includes('2 persone'));assert(nodes.get('teamMembers').innerHTML.includes('Luca'));assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0,'GPS absent member must not appear at fabricated coordinates');
presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.45,lng:15.55,acc:10,at:Date.now()})];await sync();assert.equal(ctx.__PFC_FRIEND_POINTS__()[0].name,'Luca');assert.equal(ctx.__PFC_FRIEND_POINTS__()[0].lat,41.45);
await nodes.get('pfcFriendsPause').onclick();await flush();const own=tracked.at(-1).packet;const plain=JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(own.iv,'base64url'),additionalData:new TextEncoder().encode(channel.room)},key,Buffer.from(own.data,'base64url'))));assert.equal(plain.name,'Mario');assert.equal(plain.lat,undefined,'pause must retain membership while removing location');
presence.luca=[await packet({id,name:'Luca',memberAt:Date.now(),lat:41.45,lng:15.55,acc:10,at:Date.now()-31000})];await sync();assert.equal(ctx.__PFC_FRIEND_POINTS__().length,0,'stale position must be removed from radar');delete presence.luca;await sync();assert(nodes.get('teamMemberCount').textContent.includes('1 persona'));
console.log('PASS friends: encrypted membership independent of GPS/audio, member counts, live radar coordinates, suspended and stale location removal. Mock transport, real AES-GCM.');})().catch(e=>{console.error(e);process.exit(1);});
